### ISSUE TITLE
Exception in Symfony\Component\HttpKernel\Profiler\FileProfilerStorage

### ISSUE THREAD

**Issue by zsolt-szilagyi** [FriendsOfShopware/FroshDevelopmentHelper#20] opened 2021-01-28 18:27 UTC
Generates an Exception in Symfony\Component\HttpKernel\Profiler\FileProfilerStorage write():
$data["data"]["twig"] now contains a closure, which cannot be serialized.
That throws a HTTP500 and halts the shop, in the Symfony debug bar is enabled.

**Comment by shyim** [comment] 2021-04-19 10:07
Hey,

I can't reproduce your issue. Is it still reproduceable at you?

**Comment by rabauss** [comment] 2021-05-26 15:54
I get the same error on shopware 6.4 with ``APP_ENV=dev``:
```php
request.CRITICAL: Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" 
at /xxxx/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 175
```

**Comment by shyim** [comment] 2021-05-26 15:58
What did you done and is it there also without this extension?

**Comment by rabauss** [comment] 2021-05-26 16:03
No, if I disable the extension the error does not exist.
I also disabled all other plugins so it occurs even there with the default theme and nearly only demo data!

**Comment by shyim** [comment] 2021-06-23 20:53
Idk tried now again I can't reproduce it 😓

**Comment by rabauss** [comment] 2021-06-24 10:03
With 6.4.1.1 the problem still exists in dev environment
![image](https://user-images.githubusercontent.com/14016098/123244359-2565e980-d4e4-11eb-961d-d38421f6ebdc.png)

**Comment by zaifastafa** [comment] 2021-06-26 06:13
@shyim I cannot reproduce this either. I am using PHP 7.4.20 though.

**Comment by shyim** [comment] 2021-06-26 12:56
As you are able to reproduce @rabauss could you look into the template variables which one is causing this error?

**Comment by riconeitzel** [comment] 2021-06-28 20:16
I can also see it here … it has something to do with the profiler … still looking into it

**Comment by shyim** [comment] 2021-06-28 20:35
Can you comment this out? https://github.com/FriendsOfShopware/FroshDevelopmentHelper/blob/0.3/src/Component/Profiler/TwigDataCollector.php#L29

**Comment by riconeitzel** [comment] 2021-06-28 20:46
yepp … that's it. 

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/930706/123701589-5470b800-d862-11eb-9b97-f96ad0ac55a5.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/930706/123701611-5d618980-d862-11eb-9022-b9505735acee.png">

<img width="801" alt="image" src="https://user-images.githubusercontent.com/930706/123701647-681c1e80-d862-11eb-8ee7-d003abcfbbca.png">

it looks like a recursion

<img width="882" alt="image" src="https://user-images.githubusercontent.com/930706/123701704-7b2eee80-d862-11eb-91e3-c7579e6d9633.png">

**Comment by shyim** [comment] 2021-06-28 20:51
why the fuck is the dependency container in the template vars. Under which key is it there?

**Comment by riconeitzel** [comment] 2021-06-28 21:15
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/930706/123704895-79ffc080-d866-11eb-977b-2ecb2208dee9.png">

```
$this
    ->twig
    ->renders["@Storefront/storefront/layout/header/actions/cart-widget.html.twig"]
        ["page"]
          ->cart
          ->data
          ->elements["Shopware\\Core\\Checkout\\Cart\\LineItem\\Group\\LineItemGroupBuilder"]
            ->registry
            ->packagers
            ->generator
```

**Comment by riconeitzel** [comment] 2021-06-28 21:16
This is pure TDD … "Ticket Driven Debugging" 😂

**Comment by riconeitzel** [comment] 2021-06-28 21:17
I think it's coming from here: `\Shopware\Storefront\Controller\CheckoutController::info()`

**Comment by shyim** [comment] 2021-06-28 21:28
Ahh. I will look tomorrow into it how it can be fixed in general . Thanks. That helps very much :D

**Comment by riconeitzel** [comment] 2021-06-28 21:38
Sure … if you like we can have a zoom session as well. Just ping me on slack or here! Good nite!

**Comment by shyim** [comment] 2021-06-29 19:23
Thanks fixed with https://github.com/FriendsOfShopware/FroshDevelopmentHelper/commit/e50f6bbac9e122694a52372949d0396ecc5bd4b3

I needed a promotion to reproduce it 😅

**Closed by shyim** 2021-06-29 19:23 UTC
Labels: kind/bug

**Comment by rabauss** [comment] 2021-07-07 11:49
Could you please bump the version?
